-- AlterTable
ALTER TABLE `device` MODIFY `tempLow` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    MODIFY `tempHigh` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    MODIFY `phLow` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    MODIFY `phHigh` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    MODIFY `tdoLow` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    MODIFY `tdoHigh` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    MODIFY `tdsLow` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    MODIFY `tdsHigh` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    MODIFY `turbiditiesLow` DECIMAL(10, 1) NOT NULL DEFAULT 0,
    MODIFY `turbiditiesHigh` DECIMAL(10, 1) NOT NULL DEFAULT 0;
